# Generated by Django 3.1.7 on 2021-04-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='picture',
            field=models.FileField(blank=True, default='socialnetwork/static/locationimgs/default_location_1.jpeg', upload_to='socialnetwork/static/locationimgs'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(default='socialnetwork/static/profileimgs/default_avatar.png', upload_to='socialnetwork/static/profileimgs'),
        ),
    ]
